# Gripper controller
gripper_controller:
  gripper_type: 'hand-e'
  type: position_controllers/GripperActionController
  joint: hande_left_finger_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0
  
gazebo_ros_control:
  pid_gains:
    hande_left_finger_joint:  {p: 10, d: 1, i: 0, i_clamp: 1, antiwindup: true}